export const ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  ALREADY_RUNNING: "ALREADY_RUNNING",
  INDEX_NOT_READY: "INDEX_NOT_READY",
  UNSUPPORTED_PROVIDER: "UNSUPPORTED_PROVIDER",
  AMBIGUOUS_SYMBOL: "AMBIGUOUS_SYMBOL",
  SYMBOL_NOT_FOUND: "SYMBOL_NOT_FOUND",
  ANCHOR_NOT_FOUND: "ANCHOR_NOT_FOUND",
  AMBIGUOUS_ANCHOR: "AMBIGUOUS_ANCHOR",
  ENTRYPOINT_NOT_FOUND: "ENTRYPOINT_NOT_FOUND",
  ANALYSIS_NOT_READY: "ANALYSIS_NOT_READY",
  ANALYSIS_BUDGET_EXCEEDED: "ANALYSIS_BUDGET_EXCEEDED",
  UNSUPPORTED_ANALYSIS_TARGET: "UNSUPPORTED_ANALYSIS_TARGET",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class LkgError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "LkgError";
  }
}
