export {
  getCanonicalDescriptor,
  inferSymbolIdentity,
  normalizeSymbolKind,
} from "./knowledge.js";
export type {
  AnalysisBudget,
  AnalysisCompleteness,
  AnalysisFailureClass,
  AnalysisProvenance,
  Anchor,
  AnchorKind,
  CanonicalDescriptor,
  CanonicalFactKind,
  CanonicalFactRecord,
  CodeLocation,
  DerivedFactKind,
  DerivedFactRecord,
  EvidenceItem,
  FlowSegment,
  ImpactReason,
  InternalGraphEdgeRecord,
  InternalGraphNodeRecord,
  LimitationItem,
  PrecisionTier,
  PropagationPath,
  SourceType,
  StructuredDataProvenance,
  StructuredDataScope,
  StructuredObservationKind,
  SymbolCandidateRecord,
  SymbolIdentity,
} from "./knowledge.js";
